plugins{id("com.android.application");id("org.jetbrains.kotlin.android")}
android{
 namespace="me.x.shizukuax";compileSdk=34
 defaultConfig{applicationId="me.x.shizukuax";minSdk=26;targetSdk=34;versionCode=1;versionName="1.0.0"}
 buildFeatures{viewBinding=true}
 compileOptions{sourceCompatibility=JavaVersion.VERSION_17;targetCompatibility=JavaVersion.VERSION_17}
 kotlinOptions{jvmTarget="17"}
 signingConfigs{getByName("debug"){storeFile=file("$rootDir/debug.keystore")}}
}
dependencies{
 implementation("dev.rikka.shizuku:api:13.1.5")
 implementation("androidx.webkit:webkit:1.10.0")
 implementation("androidx.core:core-ktx:1.12.0")
 implementation("androidx.appcompat:appcompat:1.6.1")
 implementation("com.google.android.material:material:1.11.0")
 implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")
 implementation("org.json:json:20231013")
}
